### ISSUE TITLE
Doesn't work with 3rd Party Login providers (Facebook, Twitter etc...)

### ISSUE THREAD

**Issue by Holf** [JustMaier/angular-spa-security#1]
Not sure this is an 'issue' as such. What you have done so far is amazing and I'm grateful for that alone.
But might you consider extending it to work with 3rd Party Login providers?

**Comment by JustMaier** [comment]
That is definitely something that I would find useful as well. I'll look into implementing support for 3rd party login providers...

**Comment by Holf** [comment]
So sorry about the 'Closed / Reopened'... slip of the mouse.

**Comment by JustMaier** [comment]
@Holf I've added 3rd party support.

**Comment by Holf** [comment]
Fantastic! Awesome job.
