### ISSUE TITLE
Return promise / block if Security.user is set

### ISSUE THREAD

**Issue by dhagan** [JustMaier/angular-spa-security#11]
I would like to ensure that Security.user is set (without having to $watch).  Is there a way to call
Security.authenticate() to return a promise, and or block until Security.user is set?

I am accessing security.user.role in child controllers.  If I can have a hook to see that user is set, then I can use a route resolver.

**Comment by dhagan** [comment]
I exposed Api as a public

Security.API = Api;

And then blocked on the promise

security.API.getUserInfo

in the route resolver.

**Comment by JustMaier** [comment]
Interesting. Mind sharing a snippet?

**Comment by dhagan** [comment]
I have a use case where the Security.user and indeed Security.user.roles needs to be populated before a (child) controller runs (we are using for a poor man's access control list).  Since user lookup is an async call, we have a race condition.

Per my comment, in angular-spa-security.js I expose Api as public

```
// expose Api as a public
Security.API = Api;
```

Using the John Papa activate() paradigm in lieu of route resolver.  
http://www.johnpapa.net/route-resolve-and-controller-activate-in-angularjs/

Here is the code I use to block the controller until getUserInfo() has returned

```
        activate();

        function activate() {
                common.activateController([getUsers()], controllerId).then(function () {
                    //console.log('indexCtrl activate() complete');
            });
        }

        // patch angular-spa-secuirty to expose  the promise to get use info. 
        // block on this to prevent race condition where Security.user might not be set in this or other controllers.
        function getUsers() {
            return security.API.getUserInfo;
        }
```

1000 Thank you's to JustMaier for publishing this helpful repo.
